version: "3.9"
services:
  api-node:
    build:
      context: .
      target: dev
    init: true
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    env_file:
      - .env.dev
    networks:
      - backend
    ports:
      - 3001:3001
    restart: unless-stopped
networks:
  backend: