version: "3.9"
services:
  api-node:
    build:
      context: .
      target: production
    init: true
    volumes:
      - nodedata:/usr/src/app
    env_file:
      - .env.dev
    networks:
      - backend
    ports:
      - 3001:3001
    restart: unless-stopped
  proxy:
    build:
      context: ./proxy
    depends_on:
      - api-node
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
volumes:
  nodedata: